### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rsplit'

### ISSUE THREAD

**Issue by KPrasch** [hangarunderground/hendrix#61]
hx start --dev

settings is defined with export.

Traceback here: http://dpaste.com/1DE3ZE8

**Comment by jMyles** [comment]
k-man, any news on this?  Are you planning on making this error message less awful?

Also, I have proposed, for use cases like yours, to allow injection of the actual application object.  #69

**Comment by jMyles** [comment]
Although this error message still sucks, I think that people are generally not going to experience it now that #69 is fixed.  @KPrasch, if you still feel otherwise, then by all means throw another try block in there.  I'm closing for now.
