### ISSUE TITLE
What's happening in the try block around run_long_function ?

### ISSUE THREAD

**Issue by jMyles** [hangarunderground/hendrix#78]
@vepkenez or @anthonyalmarza: I assume this is to make Celery optional?  I don't even really understand the point of this function anyway - can you write a quick doc for it?

https://github.com/hangarunderground/hendrix/blob/master/hendrix/contrib/async/processing.py#L91

**Comment by vepkenez** [comment]
In my opinion that whole file should be removed.

**Comment by vepkenez** [comment]
Oh, well now that CrosstownTraffic is in there, just those two task
abstractions... they are really not necessary.

**Comment by jMyles** [comment]
Actually CrosstownTraffic is not in there - that's a mistake.  It is its
own module.  So I'm +1 for deletion.

However, that will mean that we need to refactor your chat example, right?

**Comment by vepkenez** [comment]
Hmm... maybe?
There's really no point in using that send_short_task... it's more complex than just a regular deferred...

**Comment by vepkenez** [comment]
That was all written when I still believed that things like Celery were needed :-1:

**Comment by vepkenez** [comment]
Also, it looks like the chat example does not use that stuff.

**Comment by jMyles** [comment]
Awesome.  This will be a major upgrade in the readability of the async
package.
